import VideoRenderer from "./video-renderer"

const options2 = {
  id: "6LqIseL6svLDybdMzv7LM",
  type: "VIDEO",
  name: "Untitled Design",
  frame: { width: 1200, height: 1200 },
  // duration: 20,
  fps: 25,
  scenes: [
    {
      id: "1dPxLYXMiSFTNDvOa3jpr",
      duration: 3.2325,
      layers: [
        {
          id: "background",
          name: "Initial Frame",
          angle: 0,
          stroke: null,
          strokeWidth: 0,
          left: 0,
          top: 0,
          width: 1200,
          height: 1200,
          opacity: 1,
          originX: "left",
          originY: "top",
          scaleX: 1,
          scaleY: 1,
          type: "Background",
          flipX: false,
          flipY: false,
          skewX: 0,
          skewY: 0,
          visible: true,
          shadow: {
            color: "#fcfcfc",
            blur: 4,
            offsetX: 0,
            offsetY: 0,
            affectStroke: false,
            nonScaling: false,
          },
          fill: "#ffffff",
          metadata: {},
        },
        {
          id: "852399",
          name: "StaticVideo",
          angle: 0,
          stroke: null,
          strokeWidth: 0,
          left: 0,
          top: 0,
          width: 1280,
          height: 720,
          opacity: 1,
          originX: "left",
          originY: "top",
          scaleX: 0.94,
          scaleY: 0.94,
          type: "StaticVideo",
          flipX: false,
          flipY: false,
          skewX: 0,
          skewY: 0,
          visible: true,
          shadow: null,
          preview: "blob:http://localhost:5173/f623c7c6-7e4a-40c5-bbe8-df88156a32cf",
          duration: 3.2325,
          src: "https://player.vimeo.com/external/123487794.hd.mp4?s=4f76fc2a325e0e90320b25e6e12941406190c7e3&profile_id=113&oauth2_token_id=57447761",
          metadata: {},
          speedFactor: 1,
          cut: { from: 9.8218, to: 13.0543 },
        },
      ],
      name: "Untitled design",
    },
  ],
  metadata: {},
  previews: [],
}

const options = {
  duration: 10,
  fps: 25,
  frame: {
    width: 1200,
    height: 1200,
  },
  scenes: [
    {
      duration: 5,
      layers: [
        {
          id: "background",
          name: "Initial Frame",
          angle: 0,
          stroke: null,
          strokeWidth: 0,
          left: 0,
          top: 0,
          width: 1200,
          height: 1200,
          opacity: 1,
          originX: "left",
          originY: "top",
          scaleX: 1,
          scaleY: 1,
          type: "Background",
          flipX: false,
          flipY: false,
          skewX: 0,
          skewY: 0,
          visible: true,
          fill: "#8e44ad",
          metadata: {},
        },
        {
          id: "VfN7L9XFA1SaesSmGRixW",
          name: "StaticImage",
          angle: 0,
          stroke: null,
          strokeWidth: 0,
          left: 275,
          top: 252.01000000000002,
          width: 650,
          height: 650,
          opacity: 1,
          originX: "left",
          originY: "top",
          scaleX: 1,
          scaleY: 1,
          type: "StaticImage",
          flipX: false,
          flipY: false,
          skewX: 0,
          skewY: 0,
          visible: true,
          shadow: null,
          src: "https://images.pexels.com/photos/3493777/pexels-photo-3493777.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
          cropX: 0,
          cropY: 0,
          metadata: {},
        },
      ],
    },
    {
      duration: 5,
      layers: [
        {
          id: "background",
          name: "Initial Frame",
          angle: 0,
          stroke: null,
          strokeWidth: 0,
          left: 0,
          top: 0,
          width: 1200,
          height: 1200,
          opacity: 1,
          originX: "left",
          originY: "top",
          scaleX: 1,
          scaleY: 1,
          type: "Background",
          flipX: false,
          flipY: false,
          skewX: 0,
          skewY: 0,
          visible: true,
          fill: "#c0392b",
          metadata: {},
        },
        {
          id: "u7W81TCNzqKzvjcgk1bw7",
          name: "StaticImage",
          angle: 0,
          stroke: null,
          strokeWidth: 0,
          left: 275,
          top: 275,
          width: 650,
          height: 650,
          opacity: 1,
          originX: "left",
          originY: "top",
          scaleX: 1,
          scaleY: 1,
          type: "StaticImage",
          flipX: false,
          flipY: false,
          skewX: 0,
          skewY: 0,
          visible: true,
          shadow: null,
          src: "https://images.pexels.com/photos/2894944/pexels-photo-2894944.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
          cropX: 0,
          cropY: 0,
          metadata: {},
        },
      ],
    },
  ],
}
// @ts-ignore
const renderer = new VideoRenderer(options2)

// console.log(JSON.stringify(options2))

renderer
  .render()
  .then(() => console.log("DONE"))
  .catch((err) => console.log("ERROR", err))
