import VideoRenderer from "./video-renderer"

const options = {
  verbose: false,
  duration: 10,
  fps: 25,
  dimension: {
    width: 1200,
    height: 1200,
  },
  scenes: [
    {
      duration: 5,
      layers: [
        {
          id: "background",
          name: "Initial Frame",
          angle: 0,
          stroke: null,
          strokeWidth: 0,
          left: 0,
          top: 0,
          width: 1200,
          height: 1200,
          opacity: 1,
          originX: "left",
          originY: "top",
          scaleX: 1,
          scaleY: 1,
          type: "Background",
          flipX: false,
          flipY: false,
          skewX: 0,
          skewY: 0,
          visible: true,
          fill: "#8e44ad",
          metadata: {},
        },
        {
          id: "VfN7L9XFA1SaesSmGRixW",
          name: "StaticImage",
          angle: 0,
          stroke: null,
          strokeWidth: 0,
          left: 275,
          top: 252.01000000000002,
          width: 650,
          height: 650,
          opacity: 1,
          originX: "left",
          originY: "top",
          scaleX: 1,
          scaleY: 1,
          type: "StaticImage",
          flipX: false,
          flipY: false,
          skewX: 0,
          skewY: 0,
          visible: true,
          shadow: null,
          src: "https://images.pexels.com/photos/3493777/pexels-photo-3493777.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
          cropX: 0,
          cropY: 0,
          metadata: {},
        },
      ],
    },
    {
      duration: 5,
      layers: [
        {
          id: "background",
          name: "Initial Frame",
          angle: 0,
          stroke: null,
          strokeWidth: 0,
          left: 0,
          top: 0,
          width: 1200,
          height: 1200,
          opacity: 1,
          originX: "left",
          originY: "top",
          scaleX: 1,
          scaleY: 1,
          type: "Background",
          flipX: false,
          flipY: false,
          skewX: 0,
          skewY: 0,
          visible: true,
          fill: "#c0392b",
          metadata: {},
        },
        {
          id: "u7W81TCNzqKzvjcgk1bw7",
          name: "StaticImage",
          angle: 0,
          stroke: null,
          strokeWidth: 0,
          left: 275,
          top: 275,
          width: 650,
          height: 650,
          opacity: 1,
          originX: "left",
          originY: "top",
          scaleX: 1,
          scaleY: 1,
          type: "StaticImage",
          flipX: false,
          flipY: false,
          skewX: 0,
          skewY: 0,
          visible: true,
          shadow: null,
          src: "https://images.pexels.com/photos/2894944/pexels-photo-2894944.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
          cropX: 0,
          cropY: 0,
          metadata: {},
        },
      ],
    },
  ],
}

const renderer = new VideoRenderer(options)

console.log(JSON.stringify(options))

renderer
  .render()
  .then(() => console.log("DONE"))
  .catch((err) => console.log("ERROR", err))
