const template = {
  name: "Untitled design",
  objects: [
    {
      id: "background",
      name: "Initial Frame",
      angle: 0,
      stroke: null,
      strokeWidth: 0,
      left: 0,
      top: 0,
      width: 1920,
      height: 1080,
      opacity: 1,
      originX: "left",
      originY: "top",
      scaleX: 1,
      scaleY: 1,
      type: "Background",
      flipX: false,
      flipY: false,
      skewX: 0,
      skewY: 0,
      visible: true,
      metadata: {
        fill: "#ffffff",
      },
    },
    {
      angle: 0,
      stroke: "#ffffff",
      strokeWidth: 0,
      left: 720,
      top: 380.25,
      width: 640,
      height: 426,
      opacity: 1,
      originX: "left",
      originY: "top",
      scaleX: 0.75,
      scaleY: 0.75,
      type: "StaticImage",
      flipX: false,
      flipY: false,
      skewX: 0,
      skewY: 0,
      visible: true,
      metadata: {
        src: "https://pixabay.com/get/gbffb203099155e02b3b06a442aa0427ca428a035e58a3ab8bfbbd9817f0662cc6f76ec9fd7027d35902d168ab57bd298_640.jpg",
        cropX: 0,
        cropY: 0,
      },
    },
    {
      id: "E2mcHFkwGA-MTJcfl3Abs",
      angle: 0,
      stroke: "#ffffff",
      strokeWidth: 0,
      left: 352.32,
      top: 276.62,
      width: 60,
      height: 60,
      opacity: 1,
      originX: "center",
      originY: "center",
      scaleX: 4,
      scaleY: 4,
      type: "StaticPath",
      flipX: false,
      flipY: false,
      skewX: 0,
      skewY: 0,
      visible: true,
      metadata: {
        value: [["M", 60, 0], ["L", 0, 0], ["L", 0, 60], ["L", 60, 60], ["L", 60, 0], ["Z"]],
        fill: "#CBCBCB",
      },
    },
    {
      angle: 0,
      stroke: "#ffffff",
      strokeWidth: 0,
      left: 1022.02,
      top: 825.86,
      width: 800,
      height: 90.4,
      opacity: 1,
      originX: "left",
      originY: "top",
      scaleX: 1,
      scaleY: 1,
      type: "StaticText",
      flipX: false,
      flipY: false,
      skewX: 0,
      skewY: 0,
      visible: true,
      metadata: {
        fontWeight: 700,
        textAlign: "center",
        fontSize: 80,
        value: "Add a heading",
        angle: 0,
        fill: "#000000",
        charspacing: 0,
        template: "Default Text",
        lineheight: 1.16,
        text: "Default Text",
      },
    },
  ],
  background: {
    type: "color",
    value: "#ffffff",
  },
  frame: {
    width: 1920,
    height: 1080,
  },
  metadata: {
    animated: false,
  },
}
